"""set null on delete

Revision ID: 6a7affd753f9
Revises: 
Create Date: 2023-12-10 21:06:51.405443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7affd753f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_video_contents_origin_id_fkey', 'ai_video_contents', type_='foreignkey')
    op.drop_constraint('ai_video_contents_video_fusion_id_fkey', 'ai_video_contents', type_='foreignkey')
    op.create_foreign_key(None, 'ai_video_contents', 'ai_video_fusion', ['video_fusion_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ai_video_contents', 'ai_video_contents', ['origin_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('ai_video_fusion_origin_id_fkey', 'ai_video_fusion', type_='foreignkey')
    op.create_foreign_key(None, 'ai_video_fusion', 'ai_video_fusion', ['origin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_video_fusion', type_='foreignkey')
    op.create_foreign_key('ai_video_fusion_origin_id_fkey', 'ai_video_fusion', 'ai_video_fusion', ['origin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ai_video_contents', type_='foreignkey')
    op.drop_constraint(None, 'ai_video_contents', type_='foreignkey')
    op.create_foreign_key('ai_video_contents_video_fusion_id_fkey', 'ai_video_contents', 'ai_video_fusion', ['video_fusion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ai_video_contents_origin_id_fkey', 'ai_video_contents', 'ai_video_contents', ['origin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
