"""add like and view to videos

Revision ID: a6f0c6189ab8
Revises: 6a7affd753f9
Create Date: 2023-12-12 19:47:00.909099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f0c6189ab8'
down_revision: Union[str, None] = '6a7affd753f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_video_fusion', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('ai_video_fusion', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_video_fusion', 'likes')
    op.drop_column('ai_video_fusion', 'views')
    # ### end Alembic commands ###
